<%@ Page Title="Routes" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListUserRoutes.aspx.cs" Inherits="VeloEventsManager.Web.Routes.ListRoutes" %>

<asp:Content ID="Body" ContentPlaceHolderID="MainContent" runat="server">

    <asp:GridView runat="server" ID="GridViewRoutes"
        CssClass="table table-hover table-bordered" GridLines="None"
        SelectedRowStyle-CssClass="active"
        AllowPaging="true" AllowSorting="true"
        AutoGenerateColumns="false"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateSelectButton="true"
        ItemType="VeloEventsManager.Models.Route"
        DataKeyNames="Id"
        SelectMethod="GridViewRoutes_GetData"
        DeleteMethod="GridViewRoutes_DeleteItem"
        UpdateMethod="GridViewRoutes_UpdateItem">
        
        <Columns>
            <asp:BoundField DataField="Name" HeaderText="Name"/>
            <asp:BoundField DataField="LengthInMeters" HeaderText="LengthInMeters"/>
            <asp:BoundField DataField="AscentInMeters" HeaderText="AscentInMeters"/>
            <asp:BoundField DataField="DescentInMeters" HeaderText="DescentInMeters"/>
            <asp:BoundField DataField="ExpectedDurationInHours" HeaderText="ExpectedDurationInHours"/>
            <asp:TemplateField HeaderText="Present in events">
                <ItemTemplate>
                    <asp:Repeater runat="server" 
                        DataSource="<%# Item.EventDays %>" ItemType="VeloEventsManager.Models.EventDay">
                        <ItemTemplate><%#: Item.Event.Name %> <br /></ItemTemplate>
                    </asp:Repeater>
                </ItemTemplate>
            </asp:TemplateField> 
        </Columns>

    </asp:GridView>

</asp:Content>
